# Generated by Django 3.2.21 on 2023-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
